quarkus:
  datasource:
    db-kind: postgresql
    reactive:
      url: ${DATABASE_URL:postgresql://holistic:holistic@localhost:5432/holistic}
  http:
    port: ${PORT:8080}
  hibernate-orm:
    database:
      generation: drop-and-create
