quarkus:
  datasource:
    db-kind: postgresql
    reactive:
      url: ${DATABASE_URL:postgresql://holistic:holistic@localhost:5432/holistic}
      postgresql:
        ssl-mode: allow

  hibernate-orm:
    database:
      generation: drop-and-create
  http:
    port: ${PORT:8080}
  mailer:
    from: info@holisticsidhihealing.com
    host: mail.holisticsidhihealing.com
    port: 587
    trust-all: true
    login: REQUIRED
    start-tls: REQUIRED
    auth-methods: DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
    username: info@holisticsidhihealing.com
    password: ${MAIL_PASSWORD}
    mock: false

apiKey: ${RAZOR_KEY}
secretKey: ${RAZOR_SECRET}
